version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: moonpig_clone_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5439:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_main:
    image: redis:latest
    container_name: moonpig_clone_cache
    ports:
      - '6379:6379'

  redis_message_queue:
    image: redis:latest
    container_name: moonpig_clone_message_queue
    ports:
      - '6380:6379'

volumes:
  postgres_data:
