version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: outsourcd_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5439:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_main:
    image: redis:latest
    container_name: outsourcd_cache
    ports:
      - '${REDIS_CACHE_PORT}:6379'

  redis_message_queue:
    image: redis:latest
    container_name: outsourcd_message_queue
    ports:
      - '${REDIS_QUEUE_PORT}:6379'

volumes:
  postgres_data:
